"""
report_generator.py
--------------------
Generates a rich PDF report for a repository using ReportLab.

Sections:
  1. Title Page
  2. Table of Contents      (auto-generated with page numbers)
  3. Repo Overview          (LLM-generated)
  4. Architecture Summary   (LLM-generated)
  5. Directory Structure
  6. Entry Points           (LLM-generated)
  7. Dependency Analysis    (LLM-generated)
  8. Code Quality Notes     (LLM-generated)
  9. File & Function Docs   (LLM-generated per file + per function)
"""

import os
import json
from reportlab.platypus import (
    BaseDocTemplate, PageTemplate, Frame, Paragraph, Spacer,
    Image, Indenter, HRFlowable, PageBreak, KeepTogether,
)
from reportlab.platypus.tableofcontents import TableOfContents
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib.pagesizes import A3
from reportlab.lib.colors import HexColor
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfgen import canvas as pdfcanvas


# ─── Colours ──────────────────────────────────────────────────────────────────
C_DARK    = HexColor("#0f172a")
C_ACCENT  = HexColor("#38bdf8")
C_MUTED   = HexColor("#64748b")
C_TEXT    = HexColor("#1e293b")
C_CODE_BG = HexColor("#f1f5f9")
C_RULE    = HexColor("#e2e8f0")


# ─── Doc template with header/footer + TOC notification ──────────────────────

class DevDocsTemplate(BaseDocTemplate):
    def __init__(self, filename, repo_name="", **kwargs):
        super().__init__(filename, **kwargs)
        self.repo_name = repo_name

    def afterFlowable(self, flowable):
        """Notify TOC when a section heading is encountered."""
        if isinstance(flowable, Paragraph):
            style = flowable.style.name
            text  = flowable.getPlainText()
            if style == "h1":
                key = f"section-{text}"
                self.canv.bookmarkPage(key)
                self.notify("TOCEntry", (0, text, self.page, key))
            elif style == "h2":
                key = f"sub-{text}"
                self.canv.bookmarkPage(key)
                self.notify("TOCEntry", (1, text, self.page, key))

    def handle_pageBegin(self):
        super().handle_pageBegin()
        c = self.canv
        w, h = A3

        # Top bar
        c.setFillColor(C_DARK)
        c.rect(0, h - 36, w, 36, fill=1, stroke=0)
        c.setFillColor(C_ACCENT)
        c.setFont("Helvetica-Bold", 11)
        c.drawString(32, h - 22, "◈  DevDocs.ai")
        c.setFillColor(HexColor("#94a3b8"))
        c.setFont("Helvetica", 9)
        c.drawRightString(w - 32, h - 22, self.repo_name)

        # Bottom bar
        c.setFillColor(C_DARK)
        c.rect(0, 0, w, 28, fill=1, stroke=0)
        c.setFillColor(HexColor("#475569"))
        c.setFont("Helvetica", 8)
        c.drawString(32, 9, "Generated by DevDocs.ai")
        c.drawRightString(w - 32, 9, f"Page {self.page}")


# ─── Style builder ────────────────────────────────────────────────────────────

def build_styles():
    base = getSampleStyleSheet()
    s = {}

    s["title"] = ParagraphStyle("title",
        fontName="Helvetica-Bold", fontSize=38, leading=46,
        textColor=C_DARK, spaceAfter=6)

    s["subtitle"] = ParagraphStyle("subtitle",
        fontName="Helvetica", fontSize=14, leading=20,
        textColor=C_MUTED, spaceAfter=20)

    # Named "h1" so afterFlowable can detect it
    s["h1"] = ParagraphStyle("h1",
        fontName="Helvetica-Bold", fontSize=18, leading=24,
        textColor=C_DARK, spaceBefore=18, spaceAfter=6)

    # Named "h2"
    s["h2"] = ParagraphStyle("h2",
        fontName="Helvetica-Bold", fontSize=13, leading=18,
        textColor=C_DARK, spaceBefore=12, spaceAfter=4)

    s["h3"] = ParagraphStyle("h3",
        fontName="Helvetica-BoldOblique", fontSize=11, leading=15,
        textColor=HexColor("#0369a1"), spaceBefore=8, spaceAfter=3)

    s["body"] = ParagraphStyle("body",
        fontName="Helvetica", fontSize=10, leading=16,
        textColor=C_TEXT, spaceAfter=6)

    s["code"] = ParagraphStyle("code",
        fontName="Courier", fontSize=8.5, leading=13,
        textColor=HexColor("#1e293b"), backColor=C_CODE_BG,
        leftIndent=8, rightIndent=8, spaceBefore=2, spaceAfter=2,
        borderPad=4)

    s["tag"] = ParagraphStyle("tag",
        fontName="Helvetica-Bold", fontSize=8, leading=11,
        textColor=HexColor("#0369a1"), spaceAfter=2)

    s["muted"] = ParagraphStyle("muted",
        fontName="Helvetica-Oblique", fontSize=9, leading=13,
        textColor=C_MUTED, spaceAfter=4)

    # TOC entry styles
    s["toc0"] = ParagraphStyle("toc0",
        fontName="Helvetica-Bold", fontSize=12, leading=18,
        textColor=C_DARK, leftIndent=0, spaceAfter=4)

    s["toc1"] = ParagraphStyle("toc1",
        fontName="Helvetica", fontSize=10, leading=15,
        textColor=C_MUTED, leftIndent=20, spaceAfter=2)

    return s


# ─── Helpers ──────────────────────────────────────────────────────────────────

def rule(s):
    return HRFlowable(width="100%", thickness=1, color=C_RULE, spaceAfter=10, spaceBefore=4)


def section_header(title: str, s: dict):
    """Emit a section heading that gets picked up by the TOC."""
    return [
        Paragraph(title, s["h1"]),
        HRFlowable(width="100%", thickness=2, color=C_ACCENT, spaceAfter=10, spaceBefore=2),
    ]


def _md_inline(text: str) -> str:
    """
    Convert inline markdown to ReportLab XML tags.
    Code spans are extracted first so * and _ inside code
    cannot create malformed nested bold/italic tags.
    """
    import re

    # Step 1: Stash code spans using a safe placeholder (no special chars)
    placeholders = {}
    counter = [0]
    def stash_code(m):
        key = "CODESPANPLACEHOLDER" + str(counter[0]) + "END"
        counter[0] += 1
        code_text = m.group(1).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        placeholders[key] = '<font name="Courier" size="9">' + code_text + '</font>'
        return key
    text = re.sub(r'`([^`]+)`', stash_code, text)

    # Step 2: Escape XML special chars in remaining text
    text = text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")

    # Step 3: Apply bold/italic safely
    text = re.sub(r'\*\*\*(.*?)\*\*\*', r'<b><i>\1</i></b>', text)
    text = re.sub(r'\*\*(.*?)\*\*',       r'<b>\1</b>',         text)
    text = re.sub(r'__(.*?)__',             r'<b>\1</b>',         text)
    text = re.sub(r'\*(.*?)\*',            r'<i>\1</i>',         text)
    text = re.sub(r'(?<![_a-zA-Z])_([^_]+)_(?![_a-zA-Z])', r'<i>\1</i>', text)

    # Step 4: Restore code spans
    for key, val in placeholders.items():
        text = text.replace(key, val)

    return text

def _safe_para(text: str, style) -> "Paragraph":
    """Render a Paragraph, falling back to plain text if XML tags are malformed."""
    import re
    try:
        return Paragraph(text, style)
    except Exception:
        # Strip all XML/HTML tags and try again with plain text
        plain = re.sub(r'<[^>]+>', '', text)
        plain = plain.replace("&amp;", "&").replace("&lt;", "<").replace("&gt;", ">").replace("&nbsp;", " ")
        try:
            return Paragraph(plain, style)
        except Exception:
            return Paragraph("[content could not be rendered]", style)


def body_paragraphs(text: str, s: dict) -> list:
    """
    Parse GPT markdown output into ReportLab Paragraph/Spacer elements.
    Handles: # headings, ## headings, ### headings, **bold**, *italic*,
    `code`, numbered lists, bullet lists (- / *), code fences (```).
    """
    import re
    elems = []
    lines = text.split("\n")
    i = 0
    in_code_fence = False
    code_block_lines = []

    while i < len(lines):
        raw = lines[i]
        stripped = raw.strip()

        # ── Code fence open/close ──────────────────────────────────────────────
        if stripped.startswith("```"):
            if not in_code_fence:
                in_code_fence = True
                code_block_lines = []
            else:
                # Close fence — render accumulated code lines
                in_code_fence = False
                if code_block_lines:
                    for cl in code_block_lines:
                        esc = cl.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
                        elems.append(Paragraph(esc.replace(" ", "&nbsp;"), s["code"]))
                    elems.append(Spacer(1, 0.06 * inch))
                code_block_lines = []
            i += 1
            continue

        if in_code_fence:
            code_block_lines.append(raw)
            i += 1
            continue

        # ── Blank line ─────────────────────────────────────────────────────────
        if not stripped:
            elems.append(Spacer(1, 0.07 * inch))
            i += 1
            continue

        # ── ATX headings (#, ##, ###, ####) ───────────────────────────────────
        heading_match = re.match(r'^(#{1,4})\s+(.*)', stripped)
        if heading_match:
            level = len(heading_match.group(1))
            content = _md_inline(heading_match.group(2))
            style = {1: s["h1"], 2: s["h2"], 3: s["h3"], 4: s["h3"]}.get(level, s["h3"])
            elems.append(Paragraph(content, style))
            if level <= 2:
                elems.append(HRFlowable(width="100%", thickness=0.5,
                                        color=C_RULE, spaceAfter=4))
            i += 1
            continue

        # ── Numbered list  1. / 1) ────────────────────────────────────────────
        num_match = re.match(r'^(\d+)[.)]\s+(.*)', stripped)
        if num_match:
            num = num_match.group(1)
            content = _md_inline(num_match.group(2))
            bullet_style = ParagraphStyle("numlist",
                parent=s["body"], leftIndent=20, firstLineIndent=0,
                spaceBefore=2, spaceAfter=2)
            elems.append(_safe_para(f"<b>{num}.</b>&nbsp;&nbsp;{content}", bullet_style))
            i += 1
            continue

        # ── Bullet list  - / * / • ─────────────────────────────────────────────
        bullet_match = re.match(r'^[-*•]\s+(.*)', stripped)
        if bullet_match:
            content = _md_inline(bullet_match.group(1))
            bullet_style = ParagraphStyle("bullet",
                parent=s["body"], leftIndent=20, firstLineIndent=0,
                spaceBefore=2, spaceAfter=2)
            elems.append(_safe_para(f"•&nbsp;&nbsp;{content}", bullet_style))
            i += 1
            continue

        # ── Indented sub-bullet (starts with spaces + - / *) ──────────────────
        sub_bullet_match = re.match(r'^\s{2,}[-*•]\s+(.*)', raw)
        if sub_bullet_match:
            content = _md_inline(sub_bullet_match.group(1))
            sub_style = ParagraphStyle("subbullet",
                parent=s["body"], leftIndent=36, firstLineIndent=0,
                spaceBefore=1, spaceAfter=1, fontSize=9)
            elems.append(Paragraph(f"–&nbsp;&nbsp;{content}", sub_style))
            i += 1
            continue

        # ── Horizontal rule --- or === ─────────────────────────────────────────
        if re.match(r'^[-=]{3,}$', stripped):
            elems.append(HRFlowable(width="100%", thickness=0.5,
                                    color=C_RULE, spaceAfter=6, spaceBefore=6))
            i += 1
            continue

        # ── Plain paragraph ────────────────────────────────────────────────────
        content = _md_inline(stripped)
        elems.append(Paragraph(content, s["body"]))
        i += 1

    return elems


def read_readme(repo_dir: str) -> str:
    for name in ["README.md", "README.txt", "readme.md", "Readme.md"]:
        path = os.path.join(repo_dir, name)
        if os.path.exists(path):
            with open(path, "r", encoding="utf-8", errors="ignore") as fh:
                return fh.read(4000)
    return ""


# ─── Main generate function ───────────────────────────────────────────────────

def generate_report(output_path: str, repo_dir: str, _unused=None,
                    gpt_data: dict = None):
    """
    gpt_data keys (all optional, generated by server.py before calling this):
      overview, architecture, dependencies, entry_points,
      code_quality, directory_json, dir_string
    """
    gpt_data = gpt_data or {}
    # Use the real repo name passed in from server.py, not the local folder name
    repo_name = gpt_data.get("repo_name") or os.path.basename(os.path.abspath(repo_dir))

    # Font — fall back to Helvetica if not found
    font_path = os.path.join(os.path.dirname(__file__), "fonts", "SawarabiMincho-Regular.ttf")
    if os.path.exists(font_path):
        pdfmetrics.registerFont(TTFont("SawarabiMincho", font_path))
        mono_font = "SawarabiMincho"
    else:
        mono_font = "Courier"

    s = build_styles()
    s["code"].fontName = mono_font

    W, H = A3
    margin = 0.5 * inch
    frame = Frame(margin, 40, W - 2 * margin, H - 40 - 44, showBoundary=0)
    doc = DevDocsTemplate(output_path, repo_name=repo_name, pagesize=A3)
    doc.addPageTemplates([PageTemplate(id="main", frames=[frame])])

    elems = []

    # ── 1. Title page ──────────────────────────────────────────────────────────
    elems += [
        Spacer(1, 1.2 * inch),
        Paragraph("◈ DevDocs.ai", ParagraphStyle("logo",
            fontName="Helvetica-Bold", fontSize=13, textColor=C_ACCENT)),
        Spacer(1, 0.2 * inch),
        Paragraph("Repository Report", s["title"]),
        Paragraph(repo_name, ParagraphStyle("reponame",
            fontName="Helvetica-Bold", fontSize=22, textColor=C_ACCENT,
            spaceAfter=0, spaceBefore=0)),
        Spacer(1, 0.18 * inch),
        Paragraph("AI-generated documentation, architecture analysis, and code insights.",
                  s["subtitle"]),
        Spacer(1, 0.3 * inch),
        HRFlowable(width="60%", thickness=2, color=C_ACCENT),
        PageBreak(),
    ]

    # ── 2. Table of Contents ───────────────────────────────────────────────────
    toc = TableOfContents()
    toc.dotsMinLevel = 0
    toc.levelStyles = [
        ParagraphStyle("TOCHeading1",
            fontName="Helvetica-Bold", fontSize=12, leading=18,
            textColor=C_DARK, leftIndent=0, spaceAfter=4,
            endDots=ParagraphStyle("dots", fontName="Helvetica", fontSize=10,
                                   textColor=C_MUTED)),
        ParagraphStyle("TOCHeading2",
            fontName="Helvetica", fontSize=10, leading=15,
            textColor=C_MUTED, leftIndent=20, spaceAfter=2),
    ]

    elems += [
        Paragraph("Table of Contents", ParagraphStyle("toctitle",
            fontName="Helvetica-Bold", fontSize=22, leading=28,
            textColor=C_DARK, spaceAfter=6)),
        HRFlowable(width="100%", thickness=2, color=C_ACCENT,
                   spaceAfter=18, spaceBefore=4),
        toc,
        PageBreak(),
    ]

    # ── 2. Repo Overview ───────────────────────────────────────────────────────
    overview = gpt_data.get("overview", "")
    if overview:
        elems += section_header("1. Repository Overview", s)
        elems += body_paragraphs(overview, s)
        elems += [Spacer(1, 0.2 * inch), PageBreak()]

    # ── 3. Architecture Summary ────────────────────────────────────────────────
    arch = gpt_data.get("architecture", "")
    if arch:
        elems += section_header("2. Architecture Summary", s)
        elems += body_paragraphs(arch, s)
        elems += [Spacer(1, 0.2 * inch), PageBreak()]

    # ── 4. Directory Structure ─────────────────────────────────────────────────
    dir_string = gpt_data.get("dir_string", "")
    elems += section_header("3. Directory Structure", s)
    if dir_string:
        for i, line in enumerate(dir_string.split("\n")):
            esc = line.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;")
            esc = esc.replace(" ", "&nbsp;")
            st = ParagraphStyle("cs", fontName=mono_font,
                                fontSize=11 if i == 0 else 8,
                                leading=14, textColor=C_TEXT,
                                backColor=C_CODE_BG if i > 0 else None)
            elems.append(Paragraph(esc, st))
            elems.append(Spacer(1, 0.025 * inch))
    elems += [Spacer(1, 0.2 * inch), PageBreak()]

    # ── 5. Entry Points ────────────────────────────────────────────────────────
    entry = gpt_data.get("entry_points", "")
    if entry:
        elems += section_header("4. Entry Points & How to Run", s)
        elems += body_paragraphs(entry, s)
        elems += [Spacer(1, 0.2 * inch)]

    # ── 6. Dependency Analysis ─────────────────────────────────────────────────
    deps = gpt_data.get("dependencies", "")
    if deps:
        elems += section_header("5. Dependency Analysis", s)
        elems += body_paragraphs(deps, s)
        elems += [Spacer(1, 0.2 * inch), PageBreak()]

    # ── 7. Code Quality Notes ──────────────────────────────────────────────────
    quality = gpt_data.get("code_quality", "")
    if quality:
        elems += section_header("6. Code Quality Notes", s)
        elems += body_paragraphs(quality, s)
        elems += [Spacer(1, 0.2 * inch), PageBreak()]

    # ── 7. File Summaries + Function Definitions ─────────────────────────────
    directory_json = gpt_data.get("directory_json", {})
    if directory_json:
        elems += section_header("7. File & Function Documentation", s)

        def add_functions(node, current_file=None):
            if not isinstance(node, dict):
                return
            for key, value in node.items():
                if isinstance(value, dict) and "functions" in value:
                    elems.append(Spacer(1, 0.1 * inch))
                    elems.append(Paragraph(f"📄 {key}", s["h2"]))
                    elems.append(rule(s))

                    file_summary = value.get("summary")
                    if file_summary:
                        elems.extend(body_paragraphs(file_summary, s))
                        elems.append(Spacer(1, 0.08 * inch))

                    funcs = value.get("functions", [])
                    if not funcs:
                        elems.append(Paragraph("No functions found in this file.", s["muted"]))
                    for func_entry in funcs:
                        for func_name, doc in func_entry.items():
                            block = [
                                Paragraph(f"def {func_name}()", s["h3"]),
                            ]
                            if doc:
                                block.extend(body_paragraphs(doc, s))
                            else:
                                block.append(Paragraph("No documentation generated.", s["muted"]))
                            block.append(Spacer(1, 0.15 * inch))
                            elems.append(KeepTogether(block))
                elif isinstance(value, dict):
                    add_functions(value, key)

        add_functions(directory_json)

    doc.multiBuild(elems)
    print(f"-> PDF saved: {output_path}")